"""empty message

Revision ID: 67c266ace0bb
Revises: 4009fd5c8cd0
Create Date: 2017-12-12 22:07:10.102589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c266ace0bb'
down_revision = '4009fd5c8cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('body_html', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.add_column('comments', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'images', ['image_id'], ['id'])
    op.drop_column('comments', 'text')
    op.add_column('images', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('chapter_page', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'images', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'chapter_page')
    op.drop_column('images', 'author_id')
    op.add_column('comments', sa.Column('text', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'image_id')
    op.drop_column('comments', 'disabled')
    op.drop_column('comments', 'body_html')
    op.drop_column('comments', 'body')
    # ### end Alembic commands ###
