"""empty message

Revision ID: d2a335e592fa
Revises: 
Create Date: 2017-12-10 00:39:55.931531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a335e592fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comics', sa.String(length=64), nullable=True),
    sa.Column('volume', sa.String(length=64), nullable=True),
    sa.Column('chapter_num', sa.Integer(), nullable=True),
    sa.Column('chapter_name', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
