"""empty message

Revision ID: e29a63d05a11
Revises: 
Create Date: 2017-12-14 00:22:25.439541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29a63d05a11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('Image', sa.String(length=64), nullable=True))
    op.drop_column('images', 'comics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('comics', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('images', 'Image')
    # ### end Alembic commands ###
